#ifndef CUBIC_ENGINE_VERSION_H
#define CUBIC_ENGINE_VERSION_H

#define CUBIC_ENGINE_VERSION_MAJOR 
#define CUBIC_ENGINE_VERSION_MINOR 
#define CUBIC_ENGINE_VERSION_PATCH 
#define CUBIC_ENGINE_VERSION 
#endif
